apiVersion: v1
kind: Service
metadata:
  labels:
    app: snapshot-controller 
  name: snapshot-controller
  namespace: kube-system
spec:
  ports:
  - name: snapshot-controller
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: snapshot-controller
  sessionAffinity: None
  type: ClusterIP

